### PR TITLE
Hyper 1 upgrade

### LINKED ISSUE #737: Upgrade to hyper/http 1.0
Now that version 1.0 of the hyper and http* crates are out, the lambda* crates should probably follow suit. Unfortunately, it's a decently heavy lift, especially due to `Body` changing from a concrete type to a trait (https://github.com/hyperium/hyper/issues/2345). I took a stab at it, but quickly got lost in a sea of `<B: Body>`s, and figured I'd leave it to those who know the library best.

A few bits I did pick up that may come in handy for someone wanting to take this on:

- `body::to_bytes(body).await?` becomes `body.collect().await?.to_bytes()` via [`http_body_util::BodyExt`](https://docs.rs/http-body-util/latest/http_body_util/trait.BodyExt.html)
- The old `Body` becomes `BoxBody<hyper::body::Bytes, hyper::Error>` via [`http_body_util::combinators::BoxBody`](https://docs.rs/http-body-util/latest/http_body_util/combinators/struct.BoxBody.html) _if_ you want to keep it fully type-erased like it is today. Otherwise, `hyper::body::Incoming` is the right replacement type for at least most `Response`s.
- There is no more pooling http client, nor a `Connector` trait (or rather, they're relegated to [`hyper_util::client::legacy`](https://docs.rs/hyper-util/latest/hyper_util/client/legacy/index.html)). Instead, there is now [`hyper::client::conn::http1::Connection`](https://docs.rs/hyper/latest/hyper/client/conn/http1/struct.Connection.html).

### LINKED ISSUE #738: Axum 7.x causes compilation errors.
Hi 

I'm fairly new to Rust, so please advise if I'm doing something wrong. I was trying to get the [http-axum](https://github.com/awslabs/aws-lambda-rust-runtime/tree/main/examples/http-axum) example working and wanted to use the latest package dependencies. However axum 7.x no longer works - they have just [released](https://github.com/tokio-rs/axum/pull/1751) a braking change which I guess is the issue.  

I got the following error:

```
--> crates/xxxxxx/src/main.rs:45:9
    |
45  |     run(app).await
    |     --- ^^^ the trait `Service<lambda_http::http::Request<lambda_http::Body>>` is not implemented for `Router<_>`
    |     |
    |     required by a bound introduced by this call
    |
    = help: the following other types implement trait `Service<Request>`:
              <Router as Service<axum::http::Request<B>>>
              <Router as Service<IncomingStream<'_>>>
note: required by a bound in `lambda_http::run`
   --> /Users/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lambda_http-0.8.3/src/lib.rs:191:8
    |
189 | pub async fn run<'a, R, S, E>(handler: S) -> Result<(), Error>
    |              --- required by a bound in this function
190 | where
191 |     S: Service<Request, Response = R, Error = E>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `run`
```

My Cargo file dependency looks like this:

```
[dependencies]
lambda_http = "0.8.3"
lambda_runtime = "0.8.3"
tokio = { version = "1.34.0", features = ["macros"] }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["fmt"] }
axum = "0.7.1"
serde_json = "1.0.108"
```

I have downgraded in the meantime to stick to the example given but I thought I would bring this to your attention.

### PR DESCRIPTION
**Pull request by calavera**
*Issue #, if available:*

fixes #737
fixes #738 

*Description of changes:*

Hyper 1 has moved many things around, and unfortunately how to implement things now is not very clear.

- [x] Upgrade `lambda_runtime`
- [x] Upgrade `lambda_http`
- [x] Upgrade `lambda-extension`
- [x] Axum compatibility
- [x] Streaming

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

File: lambda-http/src/streaming.rs [hunk 1]
```diff
@@ -86,8 +78,16 @@ where
...
+    #[inline]
+    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
+        loop {
+            match futures_util::ready!(self.as_mut().project().body.poll_frame(cx)?) {
+                Some(frame) => match frame.into_data() {
+                    Ok(data) => return Poll::Ready(Some(Ok(data))),
+                    Err(_frame) => {}
+                },
+                None => return Poll::Ready(None),
+            }
```
Comment (bnusunny) [inline lambda-http/src/streaming.rs:90]: Instead of using loop, the following should also work.

```rust
        return match futures_util::ready!(self.as_mut().project().body.poll_frame(cx)?) {
            Some(frame) => match frame.into_data() {
                Ok(data) => Poll::Ready(Some(Ok(data))),
                Err(_frame) => Poll::Ready(None)
            },
            None => Poll::Ready(None),
        }
```

**Review by bnusunny — CHANGES_REQUESTED** [review]

**Comment by bnusunny** [comment]
Since we pull in 'Body' into this project, we probably need to use it across this project. It is re-exported in both lambda-runtime and lambda-http.

**Review by bnusunny — APPROVED** [review]
